In [2]:
import pandas as pd

turnst = pd.read_csv('turnstile_180407.txt')

In [4]:
turn_59 = turnst[turnst.STATION == '59 ST']

In [6]:
turn_59['C/A'].value_counts()

A002     504
R244     461
R245     336
R244A    294
R245A    252
C022     210
C021     168
Name: C/A, dtype: int64

In [7]:
turn_59['UNIT'].value_counts()

R051    1092
R050     755
R212     378
Name: UNIT, dtype: int64

In [8]:
turn_59['SCP'].value_counts()

00-00-00    126
01-06-00    126
01-06-01    126
00-00-02     84
00-03-00     84
00-03-02     84
01-00-03     84
01-00-02     84
01-00-01     84
01-00-00     84
00-03-01     84
00-00-03     84
00-00-01     83
02-00-01     42
02-00-00     42
01-05-01     42
01-05-00     42
00-00-04     42
00-03-03     42
00-05-02     42
00-06-02     42
00-05-01     42
00-05-00     42
00-06-01     42
01-00-04     42
02-05-01     42
02-06-00     42
01-03-00     42
02-03-05     42
02-03-04     42
02-03-06     42
02-03-01     42
02-03-00     42
02-03-03     42
02-03-02     42
00-06-00     42
02-05-00     42
Name: SCP, dtype: int64

In [12]:
turn_59.head(50)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,03/31/2018,00:00:00,REGULAR,6566463,2224050
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,03/31/2018,04:00:00,REGULAR,6566470,2224053
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,03/31/2018,08:00:00,REGULAR,6566470,2224053
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,03/31/2018,12:00:00,REGULAR,6566470,2224055
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,03/31/2018,16:00:00,REGULAR,6566470,2224055
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,03/31/2018,20:00:00,REGULAR,6566470,2224055
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/01/2018,00:00:00,REGULAR,6566470,2224055
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/01/2018,04:00:00,REGULAR,6566470,2224055
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/01/2018,08:00:00,REGULAR,6566470,2224055
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/01/2018,12:00:00,REGULAR,6566470,2224055
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/01/2018,16:00:00,REGULAR,6566470,2224055
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/01/2018,20:00:00,REGULAR,6566470,2224055
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/02/2018,00:00:00,REGULAR,6566470,2224055
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/02/2018,04:00:00,REGULAR,6566470,2224055
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/02/2018,08:00:00,REGULAR,6566495,2224142
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/02/2018,12:00:00,REGULAR,6566629,2224350
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/02/2018,16:00:00,REGULAR,6566839,2224406
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/02/2018,20:00:00,REGULAR,6567469,2224472
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/03/2018,00:00:00,REGULAR,6567630,2224496
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/03/2018,04:00:00,REGULAR,6567630,2224496
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/03/2018,08:00:00,REGULAR,6567660,2224606
21,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/03/2018,12:00:00,REGULAR,6567822,2224834
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/03/2018,16:00:00,REGULAR,6568094,2224909
23,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/03/2018,20:00:00,REGULAR,6568775,2225000
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/04/2018,00:00:00,REGULAR,6568921,2225039
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/04/2018,04:00:00,REGULAR,6568924,2225039
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/04/2018,08:00:00,REGULAR,6568955,2225144
27,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/04/2018,12:00:00,REGULAR,6569103,2225359
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/04/2018,16:00:00,REGULAR,6569377,2225415
29,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/04/2018,20:00:00,REGULAR,6570115,2225480
30,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/05/2018,00:00:00,REGULAR,6570307,2225512
31,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/05/2018,04:00:00,REGULAR,6570307,2225513
32,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/05/2018,08:00:00,REGULAR,6570338,2225613
33,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/05/2018,12:00:00,REGULAR,6570480,2225858
34,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/05/2018,16:00:00,REGULAR,6570768,2225920
35,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/05/2018,20:00:00,REGULAR,6571500,2225973
36,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/06/2018,00:00:00,REGULAR,6571707,2226010
37,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/06/2018,04:00:00,REGULAR,6571711,2226012
38,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/06/2018,08:00:00,REGULAR,6571742,2226097
39,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/06/2018,12:00:00,REGULAR,6571888,2226292
40,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/06/2018,16:00:00,REGULAR,6572205,2226369
41,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/06/2018,20:00:00,REGULAR,6572929,2226435
42,A002,R051,02-00-01,59 ST,NQR456W,BMT,03/31/2018,00:00:00,REGULAR,5889283,1316497
43,A002,R051,02-00-01,59 ST,NQR456W,BMT,03/31/2018,04:00:00,REGULAR,5889285,1316499
44,A002,R051,02-00-01,59 ST,NQR456W,BMT,03/31/2018,08:00:00,REGULAR,5889285,1316499
45,A002,R051,02-00-01,59 ST,NQR456W,BMT,03/31/2018,12:00:00,REGULAR,5889285,1316499
46,A002,R051,02-00-01,59 ST,NQR456W,BMT,03/31/2018,16:00:00,REGULAR,5889285,1316499
47,A002,R051,02-00-01,59 ST,NQR456W,BMT,03/31/2018,20:00:00,REGULAR,5889285,1316499
48,A002,R051,02-00-01,59 ST,NQR456W,BMT,04/01/2018,00:00:00,REGULAR,5889285,1316499
49,A002,R051,02-00-01,59 ST,NQR456W,BMT,04/01/2018,04:00:00,REGULAR,5889285,1316499

In [11]:
turnst.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196988 entries, 0 to 196987
Data columns (total 11 columns):
C/A                                                                     196988 non-null object
UNIT                                                                    196988 non-null object
SCP                                                                     196988 non-null object
STATION                                                                 196988 non-null object
LINENAME                                                                196988 non-null object
DIVISION                                                                196988 non-null object
DATE                                                                    196988 non-null object
TIME                                                                    196988 non-null object
DESC                                                                    196988 non-null object
ENTRIES                                                                 196988 non-null int64
EXITS                                                                   196988 non-null int64
dtypes: int64(2), object(9)
memory usage: 16.5+ MB