In [17]:
from psaw import PushshiftAPI
import pandas as pd

api = PushshiftAPI()
gen =  api.search_comments(subreddit='Seattle',before='7d')
#comments = list(gen)

In [13]:
import time

def epoch_to_time(epoch):
    return time.strftime("%a, %d %b %Y %H:%M:%S +0000", time.localtime(epoch))

In [18]:
data = []

In [21]:
for i in range(100):
    data.append(next(gen))

In [28]:
for i in data:
    if len(i) != 23:
        print(len(i))

24
24
24

In [29]:
corr_data = [i for i in data if len(i) == 23]

In [30]:
comments = pd.DataFrame(corr_data)

In [32]:
comments['time'] =comments['created'].apply(epoch_to_time)

In [33]:
comments

,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_text_color,author_flair_type,body,created_utc,id,...,retrieved_on,rte_mode,score,send_replies,stickied,subreddit,subreddit_id,created,d_,time
0,katzgar,None,None,[],None,None,text,It is rural,1524524579,dxut1hp,...,1524524580,markdown,1,True,False,Seattle,t5_2qhad,1.524550e+09,"{'author': 'katzgar', 'author_flair_background...","Mon, 23 Apr 2018 23:02:59 +0000"
1,blueblockas,None,None,[],None,None,text,Is there any sort of job market out that way n...,1524524537,dxut03s,...,1524524538,markdown,1,True,False,Seattle,t5_2qhad,1.524550e+09,"{'author': 'blueblockas', 'author_flair_backgr...","Mon, 23 Apr 2018 23:02:17 +0000"
2,blueblockas,None,None,[],None,None,text,Has Federal Way improved much in the last twen...,1524524406,dxusvp6,...,1524524409,markdown,1,True,False,Seattle,t5_2qhad,1.524550e+09,"{'author': 'blueblockas', 'author_flair_backgr...","Mon, 23 Apr 2018 23:00:06 +0000"
3,imguralbumbot,None,None,[],None,None,text,"^(Hi, I'm a bot for linking direct images of a...",1524524050,dxusjdk,...,1524524065,markdown,1,True,False,Seattle,t5_2qhad,1.524549e+09,"{'author': 'imguralbumbot', 'author_flair_back...","Mon, 23 Apr 2018 22:54:10 +0000"
4,tomosponz,None,None,[],None,None,text,Here is an open letter from a professor at Sea...,1524524043,dxusj4v,...,1524524060,richtext,1,True,False,Seattle,t5_2qhad,1.524549e+09,"{'author': 'tomosponz', 'author_flair_backgrou...","Mon, 23 Apr 2018 22:54:03 +0000"
5,blueblockas,None,None,[],None,None,text,Same thing. \n\nI also have an aging parent in...,1524523985,dxush2a,...,1524523986,markdown,1,True,False,Seattle,t5_2qhad,1.524549e+09,"{'author': 'blueblockas', 'author_flair_backgr...","Mon, 23 Apr 2018 22:53:05 +0000"
6,futureformerteacher,None,None,[],None,None,text,Your definition of suburb is just different. ...,1524523901,dxuse8e,...,1524523902,markdown,1,True,False,Seattle,t5_2qhad,1.524549e+09,"{'author': 'futureformerteacher', 'author_flai...","Mon, 23 Apr 2018 22:51:41 +0000"
7,blueblockas,None,None,[],None,None,text,Iâ€™ve got a good job and a decent house to trade!,1524523888,dxusdsm,...,1524523889,markdown,1,True,False,Seattle,t5_2qhad,1.524549e+09,"{'author': 'blueblockas', 'author_flair_backgr...","Mon, 23 Apr 2018 22:51:28 +0000"
8,Wdeflect,None,None,[],None,None,text,I guess so. I've lived in the Seattle area my ...,1524523872,dxusd9y,...,1524523878,markdown,1,True,False,Seattle,t5_2qhad,1.524549e+09,"{'author': 'Wdeflect', 'author_flair_backgroun...","Mon, 23 Apr 2018 22:51:12 +0000"
9,blueblockas,None,None,[],None,None,text,I donâ€™t distain the Midwest but this isnâ€™t my ...,1524523771,dxus9tg,...,1524523772,markdown,1,True,False,Seattle,t5_2qhad,1.524549e+09,"{'author': 'blueblockas', 'author_flair_backgr...","Mon, 23 Apr 2018 22:49:31 +0000"
10,RollingRock206,None,None,[],None,None,text,Great so now living in Seattle 4-5 years pract...,1524523721,dxus89j,...,1524523722,markdown,1,True,False,Seattle,t5_2qhad,1.524549e+09,"{'author': 'RollingRock206', 'author_flair_bac...","Mon, 23 Apr 2018 22:48:41 +0000"
11,StellarJayZ,None,flair,"[{'e': 'text', 't': 'Frallingford'}]",Frallingford,None,richtext,A veterinarian!,1524523266,dxurt6s,...,1524523268,markdown,1,True,False,Seattle,t5_2qhad,1.524548e+09,"{'author': 'StellarJayZ', 'author_flair_backgr...","Mon, 23 Apr 2018 22:41:06 +0000"
12,That_One_Guy_Inc,None,None,[],None,None,text,Also a Mexican living in Seattle...\n\nFrom wh...,1524523196,dxurqzf,...,1524523197,markdown,1,True,False,Seattle,t5_2qhad,1.524548e+09,"{'author': 'That_One_Guy_Inc', 'author_flair_b...","Mon, 23 Apr 2018 22:39:56 +0000"
13,FarToo-Young-ToDie,None,None,[],None,None,text,I am an international student who has lived in...,1524522669,dxur9ml,...,1524522671,markdown,1,True,False,Seattle,t5_2qhad,1.524548e+09,"{'author': 'FarToo-Young-ToDie', 'author_flair...","Mon, 23 Apr 2018 22:31:09 +0000"
14,BrokenGjallar,None,None,[],None,None,text,Even 5 years ago it was a shit show to look fo...,1524522475,dxur2vd,...,1524522476,markdown,1,True,False,Seattle,t5_2qhad,1.524548e+09,"{'author': 'BrokenGjallar', 'author_flair_back...","Mon, 23 Apr 2018 22:27:55 +0000"
15,BrokenGjallar,None,None,[],None,None,text,Holy shit,1524522377,dxuqzhn,...,1524522379,markdown,1,True,False,Seattle,t5_2qhad,1.524548e+09,"{'author': 'BrokenGjallar', 'author_flair_back...","Mon, 23 Apr 2018 22:26:17 +0000"
16,cucchiaio,None,flair,"[{'e': 'text', 't': 'Shoreline'}]",Shoreline,None,richtext,Thereâ€™s not much in Shoreline thatâ€™s under 650...,1524522176,dxuqsft,...,1524522177,markdown,1,True,False,Seattle,t5_2qhad,1.524547e+09,"{'author': 'cucchiaio', 'author_flair_backgrou...","Mon, 23 Apr 2018 22:22:56 +0000"
17,RollingRock206,None,None,[],None,None,text,Why would I post that if I wasn't born and rai...,1524522017,dxuqmu1,...,1524522017,markdown,1,True,False,Seattle,t5_2qhad,1.524547e+09,"{'author': 'RollingRock206', 'author_flair_bac...","Mon, 23 Apr 2018 22:20:17 +0000"
18,longlive289s,None,flair,"[{'e': 'text', 't': 'Kirkland'}]",Kirkland,None,richtext,Just praying we don't get the forest fires and...,1524521931,dxuqjsi,...,1524521932,markdown,1,True,False,Seattle,t5_2qhad,1.524547e+09,"{'author': 'longlive289s', 'author_flair_backg...","Mon, 23 Apr 2018 22:18:51 +0000"
19,cucchiaio,None,flair,"[{'e': 'text', 't': 'Shoreline'}]",Shoreline,None,richtext,Housing prices arenâ€™t really any better in Sho...,1524521879,dxuqhwj,...,1524521880,markdown,1,True,False,Seattle,t5_2qhad,1.524547e+09,"{'author': 'cucchiaio', 'author_flair_backgrou...","Mon, 23 Apr 2018 22:17:59 +0000"
20,daviator88,None,None,[],None,None,text,Who hurt you?,1524521851,dxuqgxs,...,1524521853,markdown,1,True,False,Seattle,t5_2qhad,1.524547e+09,"{'author': 'daviator88', 'author_flair_backgro...","Mon, 23 Apr 2018 22:17:31 +0000"
21,p3dal,None,None,[],None,None,text,"Based on any definition I have seen so far, I ...",1524521847,dxuqgt0,...,1524521848,markdown,1,True,False,Seattle,t5_2qhad,1.524547e+09,"{'author': 'p3dal', 'author_flair_background_c...","Mon, 23 Apr 2018 22:17:27 +0000"
22,p3dal,None,None,[],None,None,text,"On the east coast, yes, I do. Locally, I have ...",1524521816,dxuqfpt,...,1524521817,markdown,1,True,False,Seattle,t5_2qhad,1.524547e+09,"{'author': 'p3dal', 'author_flair_background_c...","Mon, 23 Apr 2018 22:16:56 +0000"
23,FarToo-Young-ToDie,None,None,[],None,None,text,Lool found the weak southerner.,1524521685,dxuqb5p,...,1524521686,markdown,1,True,False,Seattle,t5_2qhad,1.524547e+09,"{'author': 'FarToo-Young-ToDie', 'author_flair...","Mon, 23 Apr 2018 22:14:45 +0000"
24,jmicklos,None,flair,"[{'e': 'text', 't': 'East Queen Anne'}]",East Queen Anne,None,richtext,https://en.wikipedia.org/wiki/Toyota_2000GT mm...,1524521623,dxuq8z1,...,1524521625,markdown,1,True,False,Seattle,t5_2qhad,1.524547e+09,"{'author': 'jmicklos', 'author_flair_backgroun...","Mon, 23 Apr 2018 22:13:43 +0000"
25,RollingRock206,None,None,[],None,None,text,"You're not even from Seattle, don't act like y...",1524521411,dxuq1fm,...,1524521412,markdown,1,True,False,Seattle,t5_2qhad,1.524547e+09,"{'author': 'RollingRock206', 'author_flair_bac...","Mon, 23 Apr 2018 22:10:11 +0000"
26,BlaineMaverick,None,None,[],None,None,text,This. Been paying $1385 for a 2bd 1ba on Queen...,1524521238,dxupvbc,...,1524521239,markdown,1,True,False,Seattle,t5_2qhad,1.524546e+09,"{'author': 'BlaineMaverick', 'author_flair_bac...","Mon, 23 Apr 2018 22:07:18 +0000"
27,QuestionTheNWO,None,None,[],None,None,text,Uh I like to know what I'm getting?,1524521177,dxupt66,...,1524521179,markdown,1,True,False,Seattle,t5_2qhad,1.524546e+09,"{'author': 'QuestionTheNWO', 'author_flair_bac...","Mon, 23 Apr 2018 22:06:17 +0000"
28,Wordie,None,None,[],None,None,text,My god...wanting to feed one's family is now c...,1524520965,dxuplnk,...,1524520969,markdown,1,True,False,Seattle,t5_2qhad,1.524546e+09,"{'author': 'Wordie', 'author_flair_background_...","Mon, 23 Apr 2018 22:02:45 +0000"
29,GougeC,None,None,[],None,None,text,I guess that makes sense. I always just think ...,1524520479,dxup3o7,...,1524520481,markdown,1,True,False,Seattle,t5_2qhad,1.524546e+09,"{'author': 'GougeC', 'author_flair_background_...","Mon, 23 Apr 2018 21:54:39 +0000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,gweedo7,None,None,[],None,None,text,Wow is this the same troll telling someone how...,1524454061,dxt8v91,...,1524454062,markdown,1,True,False,Seattle,t5_2qhad,1.524479e+09,"{'author': 'gweedo7', 'author_flair_background...","Mon, 23 Apr 2018 03:27:41 +0000"
268,zoeyversustheraccoon,None,flair,"[{'e': 'text', 't': 'West Seattle'}]",West Seattle,None,richtext,What are your interests? And how long will yo...,1524454058,dxt8v5u,...,1524454059,markdown,1,True,False,Seattle,t5_2qhad,1.524479e+09,"{'author': 'zoeyversustheraccoon', 'author_fla...","Mon, 23 Apr 2018 03:27:38 +0000"
269,MrP32,None,None,[],None,None,text,Tell me about it! I never knew a place could h...,1524454046,dxt8uss,...,1524454046,markdown,1,True,False,Seattle,t5_2qhad,1.524479e+09,"{'author': 'MrP32', 'author_flair_background_c...","Mon, 23 Apr 2018 03:27:26 +0000"
270,Wildweed,None,flair,"[{'e': 'text', 't': 'Roy'}]",Roy,None,richtext,tbh they are lying from my lifetime perspective.,1524454026,dxt8u73,...,1524454027,markdown,1,True,False,Seattle,t5_2qhad,1.524479e+09,"{'author': 'Wildweed', 'author_flair_backgroun...","Mon, 23 Apr 2018 03:27:06 +0000"
271,Wildweed,None,flair,"[{'e': 'text', 't': 'Roy'}]",Roy,None,richtext,Please don't move here. You sound like Trump. ...,1524453895,dxt8q9o,...,1524453896,markdown,1,True,False,Seattle,t5_2qhad,1.524479e+09,"{'author': 'Wildweed', 'author_flair_backgroun...","Mon, 23 Apr 2018 03:24:55 +0000"
272,kh9228,None,None,[],None,None,text,Amtrak has a new Starliner trip that goes stra...,1524453894,dxt8q7v,...,1524453895,markdown,1,True,False,Seattle,t5_2qhad,1.524479e+09,"{'author': 'kh9228', 'author_flair_background_...","Mon, 23 Apr 2018 03:24:54 +0000"
273,Wildweed,None,flair,"[{'e': 'text', 't': 'Roy'}]",Roy,None,richtext,your welcome. come visit me next time. https:/...,1524453808,dxt8ni2,...,1524453809,markdown,1,True,False,Seattle,t5_2qhad,1.524479e+09,"{'author': 'Wildweed', 'author_flair_backgroun...","Mon, 23 Apr 2018 03:23:28 +0000"
274,kh9228,None,None,[],None,None,text,https://i.imgur.com/0rJZYPL.jpg,1524453800,dxt8n90,...,1524453803,markdown,1,True,False,Seattle,t5_2qhad,1.524479e+09,"{'author': 'kh9228', 'author_flair_background_...","Mon, 23 Apr 2018 03:23:20 +0000"
275,kh9228,None,None,[],None,None,text,"Aww man. We went to the Attic at the lodge, wh...",1524453746,dxt8ljj,...,1524453747,markdown,1,True,False,Seattle,t5_2qhad,1.524479e+09,"{'author': 'kh9228', 'author_flair_background_...","Mon, 23 Apr 2018 03:22:26 +0000"
276,kh9228,None,None,[],None,None,text,Hmmm the company I work for does have a Seattl...,1524453699,dxt8k16,...,1524453702,markdown,1,True,False,Seattle,t5_2qhad,1.524479e+09,"{'author': 'kh9228', 'author_flair_background_...","Mon, 23 Apr 2018 03:21:39 +0000"
277,iamanis,None,None,[],None,None,text,"So, be honest?",1524453671,dxt8j66,...,1524453672,markdown,1,True,False,Seattle,t5_2qhad,1.524479e+09,"{'author': 'iamanis', 'author_flair_background...","Mon, 23 Apr 2018 03:21:11 +0000"
278,iamanis,None,None,[],None,None,text,I did this trip a few summers ago. It was lon...,1524453653,dxt8ilb,...,1524453654,markdown,1,True,False,Seattle,t5_2qhad,1.524479e+09,"{'author': 'iamanis', 'author_flair_background...","Mon, 23 Apr 2018 03:20:53 +0000"
279,StellarJayZ,None,flair,"[{'e': 'text', 't': 'Frallingford'}]",Frallingford,None,richtext,The 80's.,1524453639,dxt8i4r,...,1524453640,markdown,1,True,False,Seattle,t5_2qhad,1.524479e+09,"{'author': 'StellarJayZ', 'author_flair_backgr...","Mon, 23 Apr 2018 03:20:39 +0000"
280,StellarJayZ,None,flair,"[{'e': 'text', 't': 'Frallingford'}]",Frallingford,None,richtext,Maybe he went back to Texas. Everyone from Tex...,1524453521,dxt8ear,...,1524453523,markdown,1,True,False,Seattle,t5_2qhad,1.524479e+09,"{'author': 'StellarJayZ', 'author_flair_backgr...","Mon, 23 Apr 2018 03:18:41 +0000"
281,WalleyeEnthusiast,None,None,[],None,None,text,"I have been contemplating changing careers, ma...",1524453263,dxt85qx,...,1524453264,markdown,1,True,False,Seattle,t5_2qhad,1.524478e+09,"{'author': 'WalleyeEnthusiast', 'author_flair_...","Mon, 23 Apr 2018 03:14:23 +0000"
282,mjmcaulay,None,None,[],None,None,text,"Too late, I moved here from Orange County 8 ye...",1524453253,dxt85fd,...,1524453255,markdown,1,True,False,Seattle,t5_2qhad,1.524478e+09,"{'author': 'mjmcaulay', 'author_flair_backgrou...","Mon, 23 Apr 2018 03:14:13 +0000"
283,Gran8apfel,None,None,[],None,None,text,Thanks buddy. God bless.,1524453226,dxt84k3,...,1524453227,markdown,1,True,False,Seattle,t5_2qhad,1.524478e+09,"{'author': 'Gran8apfel', 'author_flair_backgro...","Mon, 23 Apr 2018 03:13:46 +0000"
284,MrsWhatsit-75,None,None,[],None,None,text,My husband would like to know when these clust...,1524453046,dxt7z3r,...,1524453047,markdown,1,True,False,Seattle,t5_2qhad,1.524478e+09,"{'author': 'MrsWhatsit-75', 'author_flair_back...","Mon, 23 Apr 2018 03:10:46 +0000"
285,Anish_Does_Stuff,None,None,[],None,None,text,"Well the space needle, the aquarium, the zoo I...",1524452827,dxt7sfa,...,1524452828,markdown,1,True,False,Seattle,t5_2qhad,1.524478e+09,"{'author': 'Anish_Does_Stuff', 'author_flair_b...","Mon, 23 Apr 2018 03:07:07 +0000"
286,TheAsbestosFestus,None,None,[],None,None,text,"while you're at the gum wall, be sure to help ...",1524452781,dxt7qyf,...,1524452783,markdown,1,True,False,Seattle,t5_2qhad,1.524478e+09,"{'author': 'TheAsbestosFestus', 'author_flair_...","Mon, 23 Apr 2018 03:06:21 +0000"
287,KireMac,None,None,[],None,None,text,I'm coming to the falls Thursday for my gf bir...,1524452727,dxt7pa7,...,1524452728,markdown,1,True,False,Seattle,t5_2qhad,1.524478e+09,"{'author': 'KireMac', 'author_flair_background...","Mon, 23 Apr 2018 03:05:27 +0000"
288,TheAsbestosFestus,None,None,[],None,None,text,They closed down the Brown Bear self-service c...,1524452688,dxt7o0w,...,1524452689,markdown,1,True,False,Seattle,t5_2qhad,1.524478e+09,"{'author': 'TheAsbestosFestus', 'author_flair_...","Mon, 23 Apr 2018 03:04:48 +0000"
289,TheAsbestosFestus,None,None,[],None,None,text,"Where I live, the rules say you are not allowe...",1524452561,dxt7jwd,...,1524452562,markdown,1,True,False,Seattle,t5_2qhad,1.524478e+09,"{'author': 'TheAsbestosFestus', 'author_flair_...","Mon, 23 Apr 2018 03:02:41 +0000"
290,highcontrastgrey,None,None,[],None,None,text,The Market is a great place to start from. I w...,1524452549,dxt7jjk,...,1524452550,markdown,1,True,False,Seattle,t5_2qhad,1.524478e+09,"{'author': 'highcontrastgrey', 'author_flair_b...","Mon, 23 Apr 2018 03:02:29 +0000"
291,Skier604,None,None,[],None,None,text,Lenyâ€™s in Tangletown/Green Lake.,1524452493,dxt7hrh,...,1524452495,markdown,1,True,False,Seattle,t5_2qhad,1.524478e+09,"{'author': 'Skier604', 'author_flair_backgroun...","Mon, 23 Apr 2018 03:01:33 +0000"
292,SounderBruce,None,flair,"[{'e': 'text', 't': 'Snohomish County'}]",Snohomish County,None,richtext,Almost all of Everett can be described as subu...,1524452378,dxt7e8s,...,1524452378,markdown,1,True,False,Seattle,t5_2qhad,1.524478e+09,"{'author': 'SounderBruce', 'author_flair_backg...","Mon, 23 Apr 2018 02:59:38 +0000"
293,TheAsbestosFestus,None,None,[],None,None,text,A neighbor of mine got a dog from a shelter. ...,1524452272,dxt7aym,...,1524452273,markdown,1,True,False,Seattle,t5_2qhad,1.524477e+09,"{'author': 'TheAsbestosFestus', 'author_flair_...","Mon, 23 Apr 2018 02:57:52 +0000"
294,SounderBruce,None,flair,"[{'e': 'text', 't': 'Snohomish County'}]",Snohomish County,None,richtext,Snohomish County is the smallest taxbase in th...,1524452132,dxt76i5,...,1524452133,markdown,1,True,False,Seattle,t5_2qhad,1.524477e+09,"{'author': 'SounderBruce', 'author_flair_backg...","Mon, 23 Apr 2018 02:55:32 +0000"
295,vuudoodude,None,None,[],None,None,text,Tell all your friends that our weather sucks a...,1524452099,dxt75g0,...,1524452101,markdown,1,True,False,Seattle,t5_2qhad,1.524477e+09,"{'author': 'vuudoodude', 'author_flair_backgro...","Mon, 23 Apr 2018 02:54:59 +0000"
296,okaw,None,None,[],None,None,text,You should probably stick with that.,1524452081,dxt74u8,...,1524452083,markdown,1,True,False,Seattle,t5_2qhad,1.524477e+09,"{'author': 'okaw', 'author_flair_background_co...","Mon, 23 Apr 2018 02:54:41 +0000"